apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8s-deployment
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: spring-boot-k8s
          image: adijaiswal/shopping-kart:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8070
          resources:
            requests:
              memory: "256Mi" # Request 256 MiB of memory
              cpu: "250m"      # Request 250 millicores (0.25 cores) of CPU
            limits:
              memory: "512Mi" # Limit to 512 MiB of memory
              cpu: "500m"      # Limit to 500 millicores (0.5 cores) of CPU
              
---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: springboot-k8ssvc
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: "TCP"
      port: 8070 # The port that the service is running on in the cluster
      targetPort: 8070 # The port exposed by the service
  type: NodePort # type of the service.
